import React from 'react';
import { Cpu, Terminal, Clock } from 'lucide-react';

/**
 * AI Insight Panel
 * Displays structured NLP insights generated by the backend AI engine.
 * Accessible: uses aria-live region so screen readers are notified of new insights.
 */
export default function InsightPanel({ insights }) {
  return (
    <section
      className="glass-panel insight-container"
      role="complementary"
      aria-label="AI Operations Intelligence Feed"
    >
      <h2 className="section-title">
        <Cpu size={18} className="icon-ai" aria-hidden="true" /> AI Operations Intelligence
      </h2>

      <div
        className="insight-scroll-area"
        role="log"
        aria-live="polite"
        aria-atomic="false"
        aria-label="Live AI insights feed"
        aria-busy={insights.length === 0}
      >
        {insights.length === 0 ? (
          <div className="empty-state" aria-label="Processing AI insights">
            <Terminal size={32} aria-hidden="true" />
            <p>Processing flow momentum coefficients...</p>
          </div>
        ) : (
          insights.map((insight, index) => (
            <article
              key={index}
              className={`insight-card severity-${insight.severity.toLowerCase()}`}
              aria-label={`${insight.severity} priority insight for ${insight.zone.replace('_', ' ')}`}
            >
              <div className="insight-header">
                <span className="severity-badge" aria-label={`Severity: ${insight.severity}`}>
                  {insight.severity}
                </span>
                <span className="zone-tag">{insight.zone.replace('_', ' ')}</span>
              </div>
              <p className="insight-message">{insight.message}</p>
              <div className="insight-action" role="note" aria-label="Recommended action">
                <strong>Recommended:</strong> {insight.action}
              </div>
              <div className="insight-footer">
                <Clock size={12} aria-hidden="true" />
                <span aria-label="Time: Just now">Just now</span>
              </div>
            </article>
          ))
        )}
      </div>
    </section>
  );
}
